In [51]:
import numpy as np

### 1. 初始化陣列

In [147]:
# 使用Python 列表建立陣列
np1 = np.array([1,3,5])
np2 = np.array([[1,2,],[3,4],[5,6]])
print(np1)
print(np2)

[1 3 5]
[[1 2]
 [3 4]
 [5 6]]


In [114]:
# 使用Numpy arange函數建立連續數值陣列
np3 = np.arange(1,10)
print(np3)

[1 2 3 4 5 6 7 8 9]


In [115]:
# 使用Numpy linspace函數建立連續等距數值陣列
p4 = np.linspace(0,4,11)
print(np4)

[0.  0.4 0.8 1.2 1.6 2.  2.4 2.8 3.2 3.6 4. ]


In [116]:
# 建立填滿 0 的陣列
np5 = np.zeros([2, 3]) 
print (np5)

[[0. 0. 0.]
 [0. 0. 0.]]


In [117]:
# 建立填滿 1 的陣列
np6 = np.ones([2, 3]) 
print (np6)

[[1. 1. 1.]
 [1. 1. 1.]]


In [131]:
# 建立對角線為1的對角矩陣陣列
np7 = np.eye(10) 
print(np7)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [148]:
#建立隨機數值陣列
#rand : 给定維度生成[0,1)之間的數值陣列，包含0，不包含1
np8 = np.random.rand(5) 
print(np8)
np9 = np.random.rand(4,2)
print(np9)
np10 = np.random.rand(4,3,2)
print(np10)

[0.36989345 0.54425216 0.72736689 0.55142687 0.61343442]
[[0.84960141 0.41804866]
 [0.65697134 0.93242409]
 [0.79457993 0.52826627]
 [0.41929693 0.03234124]]
[[[0.92681376 0.99739263]
  [0.52983884 0.82472698]
  [0.69350524 0.75516638]]

 [[0.6438198  0.14599879]
  [0.52058678 0.69437123]
  [0.40382765 0.74797413]]

 [[0.88184933 0.71812934]
  [0.97105638 0.69820825]
  [0.65152153 0.82539504]]

 [[0.25237835 0.82016872]
  [0.15856971 0.1541679 ]
  [0.97935496 0.08717885]]]


In [146]:
#randn : 给定維度生成常態分佈的數值陣列 , N（0，1）
np11 = np.random.randn(5) 
print(np11)
np12 = np.random.randn(4,2)
print(np12)
np13 = np.random.randn(4,3,2)
print(np13)

[-0.49387758 -0.24131772  1.18895472 -0.33827806 -0.65538614]
[[ 1.63426667 -0.49857565]
 [-0.13303717  1.62313097]
 [-0.65992561 -1.40966686]
 [-1.13652444  0.59255345]]
[[[ 0.10236435  1.18040883]
  [ 1.7736878   1.10642261]
  [-1.89569139  0.03373473]]

 [[ 2.03588557  1.73860058]
  [-0.84300473 -0.47656762]
  [ 1.41192721  0.94331434]]

 [[ 0.70545889  0.16277723]
  [-1.85759215 -0.66567973]
  [-0.49702525  0.96509961]]

 [[-0.71702437  0.03147036]
  [-0.11514881  1.42005079]
  [ 0.85770348  0.62239384]]]


In [154]:
#randint : 给定維度生成隨機整數數值陣列 
np14 = np.random.randint(6,size=5) 
print(np14)
np15 = np.random.randint(2,10)
print(np15)
np16 = np.random.randint(-10,10,size=(2,2))
print(np16)

[1 1 0 0 3]
2
[[-1  5]
 [-4  6]]


In [166]:
#从给定的一维陣列中生成随數值
demo_list = [10, 20,30,40, 50]
#demo_list = ['lenovo', 'sansumg','moto','xiaomi', 'iphone']
np.random.choice(demo_list,size=(2,5), p=[0.1,0.6,0.1,0.1,0.1])

array([[30, 20, 10, 10, 20],
       [20, 20, 40, 20, 40]])

In [167]:
#  從檔CSV案讀取資料
np7 = np.genfromtxt('data/data.csv', delimiter=',')
print(np7)

[[ 1. 10. 20. 30. 40. 50. 60.]
 [ 2. 12. 22. 32. 42. 52. 62.]]


### 2. 陣列索引訪問

In [156]:
#一維照列
np1 = np.arange(0,10)
print(np1)
print("np1[0] ={%s},np1[5] ={},np1[-1] ={}",np1[0],np1[5],np1[-2])
print("np1[:5] = ",np1[:5])
print("np1[3:7] = ",np1[3:7])
print("np1[6:] = ",np1[6:])
print(np1[1:6:2])
print(np1[1::2])
print(np1[::3])

[0 1 2 3 4 5 6 7 8 9]
np1[0] ={%s},np1[5] ={},np1[-1] ={} 0 5 8
np1[:5] =  [0 1 2 3 4]
np1[3:7] =  [3 4 5 6]
np1[6:] =  [6 7 8 9]
[1 3 5]
[1 3 5 7 9]
[0 3 6 9]


In [128]:
#二維照列







### 操作運算

In [43]:



np3 =np1+np2

print(np3)
print(np1.ndim, np1.shape, np1.dtype)
np3 = np.array([1, 2, 3, 4, 5, 6])
print(np3)
np3 = np.array([1, 2, 3, 4, '5', 6])
print(np3,np3.dtype)


[ 3  7 11]
1 (3,) int64
[1 2 3 4 5 6]
['1' '2' '3' '4' '5' '6'] <U21


[[ 1. 10. 20. 30. 40. 50. 60.]
 [ 2. 12. 22. 32. 42. 52. 62.]]


### 改變陣列維度

In [28]:
npd = npd.reshape([7,2])
print(npd)

[[ 1. 10.]
 [20. 30.]
 [40. 50.]
 [60.  2.]
 [12. 22.]
 [32. 42.]
 [52. 62.]]


[[0. 0. 0.]
 [0. 0. 0.]]


** 建立填滿 1 的陣列

In [32]:
np1 = np.ones([2, 3]) 
print (np1)

[[1. 1. 1.]
 [1. 1. 1.]]


### 陣列索引與切片

In [33]:
np3 = np.array([1, 2, 3, 4, 5, 6])
print(np3[2])

3


In [35]:
np3 = np3.reshape([2, 3])
print(np3[1, 0])

4


### 使用布林遮罩來取值

In [36]:
np3 = np.array([1, 2, 3, 4, 5, 6])
print(np3 > 3)

[False False False  True  True  True]


In [37]:
print(np3[np3 > 3])

[4 5 6]


In [41]:
np3 = np3.reshape([3, 2])
print(np3)
print(np3.sum(axis=1)) # 將 axis=1 橫向加總 [6 15]
print(np3.sum(axis=0)) # 將 axis=1 橫向加總 [6 15]

[[1 2]
 [3 4]
 [5 6]]
[ 3  7 11]
[ 9 12]
